begin;
select extensions.plan(16);
select extensions.ok(pg_catalog.to_regclass('private.provider_credential_references') is not null, 'P6T12-CRED-001 registry exists');
select extensions.ok(pg_catalog.to_regclass('private.provider_credential_reference_audit_events') is not null, 'P6T12-CRED-001 audit exists');
select extensions.ok(not pg_catalog.has_table_privilege('anon','private.provider_credential_references','select,insert,update,delete'), 'P6T12-CRED-003 anon denied');
select extensions.ok(not pg_catalog.has_table_privilege('provider_credential_reference_reader','private.provider_credential_references','select,insert,update,delete'), 'P6T12-CRED-004 reader table denied');
select extensions.ok(not pg_catalog.has_table_privilege('provider_credential_reference_provisioner','private.provider_credential_references','select,insert,update,delete'), 'P6T12-CRED-005 provisioner table denied');
select * from private.provision_provider_credential_reference('BITGO','TEST','SYNTHETIC_REFERENCE','00000000-0000-4000-8000-000000120001','SYNTHETIC_PROVISION');
select extensions.is((select version from private.provider_credential_references),1::bigint,'P6T12-CRED-006 provision version');
select extensions.is((select reference_id from private.load_active_provider_credential_reference('BITGO','TEST')),'SYNTHETIC_REFERENCE','P6T12-CRED-007 metadata load');
select extensions.throws_ok($$select * from private.provision_provider_credential_reference('BITGO','TEST','SECOND_REFERENCE','00000000-0000-4000-8000-000000120002','SYNTHETIC_DUPLICATE')$$,'23505','credential_reference_current_exists','P6T12-CRED-008 uniqueness');
select * from private.rotate_provider_credential_reference((select id from private.provider_credential_references),1,'ROTATED_REFERENCE','00000000-0000-4000-8000-000000120003','SYNTHETIC_ROTATE');
select extensions.is((select version from private.provider_credential_references),2::bigint,'P6T12-CRED-009 rotate increments');
select extensions.throws_ok($$select * from private.rotate_provider_credential_reference((select id from private.provider_credential_references),1,'STALE_REFERENCE','00000000-0000-4000-8000-000000120004','SYNTHETIC_STALE')$$,'23514','credential_reference_version_conflict','P6T12-CRED-010 stale conflict');
select * from private.revoke_provider_credential_reference((select id from private.provider_credential_references),2,'00000000-0000-4000-8000-000000120005','SYNTHETIC_REVOKE');
select extensions.is((select lifecycle from private.provider_credential_references),'REVOKED','P6T12-CRED-011 revoked');
select extensions.throws_ok($$select * from private.load_active_provider_credential_reference('BITGO','PRODUCTION')$$,'42501','credential_reference_read_not_authorized','P6T12-CRED-014 isolation');
select extensions.ok((select count(*) from information_schema.columns where table_schema='private' and table_name='provider_credential_references' and column_name ~* 'secret|token|bearer')=0,'P6T12-CRED-016 no secret column');
select extensions.ok((select count(*) from information_schema.columns where table_schema='private' and table_name='provider_credential_reference_audit_events' and column_name ~* 'secret|token|bearer')=0,'P6T12-CRED-017 no audit secret');
select extensions.ok(not pg_catalog.has_function_privilege('authenticated','private.load_active_provider_credential_reference(text,text)'::regprocedure,'execute'),'P6T12-CRED-003 browser function denied');
select extensions.is((select count(*) from private.provider_credential_reference_audit_events),3::bigint,'P6T12-CRED-028 audit exact');
select * from extensions.finish(); rollback;
